---
 - hosts: local
   sudo: yes
   tasks:
     # Pull eat infrastructure
     - name: pull infrastructure repo
       command: git clone https://github.com/CSUN-SeniorDesign/eat-infrastructure.git

     # Git clone the repository onto the blog machine
     - name: grab the blog files from the git repository
       command: git clone https://github.com/CSUN-SeniorDesign/eat-blog.git

     # Download and install Hugo
     - name: download and install hugo
       command: snap install hugo

     # Create hugo directory
     - name: create hugo directory
       command: mkdir /home/ubuntu/beats

     # Use Hugo to create a site
     - name: create site using hugo
       command: hugo new site beats

     # Clone the git repo that holds the "dream" theme
     - name: clone git repo for hugo theme
       command: git clone https://github.com/g1eny0ung/hugo-theme-dream.git

     # Make themes file
     - name: make themes file
       command: mkdir /home/ubuntu/beats/content/post

     # Copy files
     - name: move files from dream to beats
       command: mv /home/ubuntu/hugo-theme-dream/ /home/ubuntu/beats/themes/

     # Move files
     - name: move files
       command: mv /home/ubuntu/eat-blog /home/ubuntu/beats/content/post/

     # Remove default config
     - name: remove config
       command: rm /home/ubuntu/beats/config.toml

     # Move infrastructure file
     - name: move infrastructure file
       command: mv /home/ubuntu/eat-infrastructure/"Project 1"/Ansible/config.toml /home/ubuntu/beats/

     # Run hugo
     - name: create site using hugo command
       command: hugo
       args:
         chdir: /home/ubuntu/beats

     # Delete HTML file
     - name: remove html file
       command: rmdir /var/www/html

     # Rename public file
     - name: rename public file
       command: mv /home/ubuntu/beats/public /home/ubuntu/beats/html

     # Move beats html to var www
     - name: move beats html to var www
       command: mv /home/ubuntu/beats/html /var/www
