---
  - hosts: local
    sudo: yes
    tasks:
      # Apache 2 is required to host webpages
      - name: install apache2
        apt: name=apache2 update_cache=yes state=latest

      # Python-pip is required for hugo commands 
      - name: install python-pip
        apt: name=python-pip update_cache=yes state=latest

      # Git is required for version control
      - name: install git
        apt: name=git update_cache=yes state=latest

      # Remove html folder from /var/www
      - name: remove html folder
        command: rm -rf /var/www/html/
